cc_library(
	name="spartan",
    visibility = ["//visibility:public"],
    srcs =["vector.cxx",
"sparse_types.cxx",
"preconditioner.cxx",
"hsc_preconditioner.cxx"],
	hdrs =["allocators.h",
	       "vector.h",
	       "sparse_types.h",
	       "preconditioner.h",
	       "hsc_preconditioner.h",
	       "pcg.h"],
)